import Link from "next/link";
import "../styles/global.css";
import { useRouter } from "next/router";
import Header from "../components/header";

export const metadata = {
  title: "next test",
  description: "Generated by create next app",
};

export default function App({ Component, pageProps }) {
  const router = useRouter();

  return (
    <>
      <Header />
      <Component {...pageProps} />
      <p>Footer</p>
    </>
  );
}
